/**
 * MEMBER 2 - Fandom Content
 * Demo seeder for the Fandom Hub, News, Gallery, Video Player, Podcasts,
 * Discover feed and the Beginner Fan glossary.
 *
 * Run:  node database/seedContent.js     (or)  npm run seed:content
 *
 * Every `image_url` points at a bundled asset generated by
 * frontend/tool/generate_banner_art.py, so the app always renders real
 * artwork instead of placeholders.
 *
 * Safe to run multiple times - existing rows are refreshed, never duplicated.
 */

import "./db.js";
import { initContentSchema } from "./contentSchema.js";
import { all, get, run } from "./dbhelpers.js";

initContentSchema();

const IMG = "assets/images/content";
const FANDOM_IMG = "assets/images/fandoms";

/** ISO-ish date N days in the past, so "Latest Updates" is always fresh. */
function daysAgo(days, hour = 9) {
  const date = new Date(Date.now() - days * 86400000);
  date.setHours(hour, 0, 0, 0);
  return date.toISOString().slice(0, 19).replace("T", " ");
}

// ---------------------------------------------------------------------------
// news + articles + deep dives
// ---------------------------------------------------------------------------
const ARTICLES = [
  {
    fandom: "Anime", hub: "anime", type: "news",
    title: "One Piece: Wano finale sets a new streaming record",
    subtitle: "4.2 million fans watched live",
    summary: "The Wano arc finale became the most watched anime episode of the season, with fans trending five separate hashtags worldwide.",
    body:
      "The finale closed a storyline that ran for more than four years of production, and the reaction online was immediate.\n\nStreaming platforms reported 4.2 million concurrent viewers during the first hour alone. Fan communities organised watch parties across 60 cities, and cosplay groups recreated the final battle on social feeds within a day.\n\nWhat made this episode land so well was the pacing. Instead of stacking cliffhangers, the studio gave every main character a quiet moment before the final clash, which is exactly what long-time readers wanted to see animated.\n\nLooking ahead, the next arc has already been teased. Production staff confirmed a short break before the new season begins.",
    image: `${IMG}/news_01.jpg`, author: "Fandom Verse Desk", source: "Fandom Verse Newsroom",
    tags: "OnePiece,Wano,Anime", featured: 1, daysAgo: 1, views: 18420, likes: 1320, comments: 214,
  },
  {
    fandom: "Gaming", hub: "gaming", type: "news",
    title: "Community speedrun breaks a three-year-old RPG world record",
    subtitle: "Route was found by six players together",
    summary: "A group of runners shaved 41 seconds off a record that had stood since 2022, then published the full route notes for everyone.",
    body:
      "What started as a joke in a Discord call turned into a new world record. Six runners spent three weeks testing a skipped cutscene that nobody thought was possible.\n\nThe trick depends on a frame-perfect movement input, so the run is risky - roughly half of the attempts died on the second boss. The record holder lost the lead twice in the same night before landing a clean run.\n\nAs is tradition in the community, the route file, split timings and video commentary were released within hours. That openness is the reason the community keeps finding new ground.",
    image: `${IMG}/news_02.jpg`, author: "Rahul Verma", source: "Speedrun Community Board",
    tags: "Speedrun,Esports,Gaming", featured: 1, daysAgo: 2, views: 9310, likes: 742, comments: 96,
  },
  {
    fandom: "Movies & TV", hub: "movies-tv", type: "news",
    title: "Cosmic saga season 3 teaser drops a hidden villain clue",
    subtitle: "Frame 41 is doing a lot of work",
    summary: "Eagle-eyed fans spotted a familiar insignia in the background of the new teaser - and the showrunner just liked a fan theory.",
    body:
      "The 90-second teaser looked straightforward until fans paused at the 41st frame. A projection on the wall matches an insignia last seen in the prequel trilogy.\n\nWithin a day, three deep-dive breakdowns had been posted, and the showrunner liked one of them before removing the like. That is as close to confirmation as this fandom usually gets.\n\nSeason 3 arrives later this year. The cast panel happens at Comic-Con, so expect a full trailer then.",
    image: `${IMG}/news_03.jpg`, author: "Daniel Silva", source: "Screen Fanatics",
    tags: "SciFi,Trailer,CosmicSaga", featured: 1, daysAgo: 3, views: 12240, likes: 968, comments: 158,
  },
  {
    fandom: "Comics", hub: "comics", type: "news",
    title: "Indie graphic novel takes the biggest award of the year",
    subtitle: "A self-published debut beat the big two",
    summary: "A 180-page debut graphic novel won best original work, beating two flagship superhero titles in the process.",
    body:
      "The win is a genuine surprise. The book was funded by a small crowdfunding campaign and printed in a run of 2,000 copies, which sold out twice.\n\nThe judges highlighted the lettering and colour work, and the creator thanked their local comic shop on stage.\n\nA sequel has been confirmed for next spring, with the first printing already open for pre-orders.",
    image: `${IMG}/news_04.jpg`, author: "Daniel Silva", source: "Panel & Ink Weekly",
    tags: "Indie,Awards,Comics", featured: 1, daysAgo: 4, views: 6120, likes: 531, comments: 74,
  },
  {
    fandom: "Music", hub: "music", type: "news",
    title: "K-Pop group announces a world tour with 12 new stops",
    subtitle: "Ticket presale opens next week",
    summary: "The tour adds stadium dates across four continents, and the fan-club presale opens before general sale for the first time.",
    body:
      "The tour dates were revealed with a 20-second video that already has more than 9 million views.\n\nNotably, fan-club members get a 48-hour window before general sale, and light-stick synchronisation will be supported at every stop except two (the venues have older hardware).\n\nStreaming numbers for the new mini-album went up 40% in the 24 hours after the announcement.",
    image: `${IMG}/news_05.jpg`, author: "Aisha Khan", source: "Idol Watch",
    tags: "KPop,Tour,Comeback", featured: 1, daysAgo: 5, views: 15330, likes: 1840, comments: 402,
  },
  {
    fandom: "Sci-Fi", hub: "sci-fi", type: "news",
    title: "Cyberpunk series renewed for two more seasons",
    subtitle: "Production starts this autumn",
    summary: "The streaming service confirmed a double renewal, and the writers' room is already mapping the final arc.",
    body:
      "Two seasons at once is unusual, but the show is one of the platform's most re-watched titles. Weekly watch numbers actually grew during the second half of season 2.\n\nThe creators have promised that the ending is planned out and will not be extended beyond season 4.\n\nA tie-in audio drama set between seasons is also in development.",
    image: `${IMG}/news_06.jpg`, author: "Fandom Verse Desk", source: "Fandom Verse Newsroom",
    tags: "Cyberpunk,Renewal,SciFi", featured: 0, daysAgo: 6, views: 4870, likes: 388, comments: 51,
  },
  {
    fandom: "Anime", hub: "anime", type: "news",
    title: "Studio reveals a behind-the-scenes look at the new film",
    subtitle: "2,400 hand-drawn cuts",
    summary: "The production documentary shows how the team combined traditional key animation with a fully 3D background pipeline.",
    body:
      "The 18-minute documentary follows three animators through a single action sequence. It took eleven weeks to complete and used 2,400 hand-drawn cuts.\n\nDirectors explain that the background pipeline is fully 3D, but every character frame is still drawn by hand.\n\nThe film opens in cinemas next month, with subtitled and dubbed screenings on the same day.",
    image: `${IMG}/news_07.jpg`, author: "Mei Tanaka", source: "Animation Weekly",
    tags: "Studio,Film,Animation", featured: 0, daysAgo: 7, views: 7310, likes: 604, comments: 88,
  },
  {
    fandom: "Gaming", hub: "gaming", type: "news",
    title: "Open-world RPG adds the photo mode fans asked for",
    subtitle: "Patch 4.2 is live now",
    summary: "After two years of requests, patch 4.2 adds a full photo mode with time-of-day control and a depth-of-field slider.",
    body:
      "The photo mode includes 40 filters, focal length control and a freeze-frame option for combat.\n\nThe community's first reaction was predictable: within six hours, the screenshot tag had 20,000 new posts, and three of them are now in-game loading screens.\n\nThe patch also fixes the frame-rate drops reported in the northern region.",
    image: `${IMG}/news_08.jpg`, author: "Rahul Verma", source: "Patch Notes Daily",
    tags: "Patch,PhotoMode,RPG", featured: 0, daysAgo: 8, views: 5540, likes: 470, comments: 63,
  },
  {
    fandom: "Movies & TV", hub: "movies-tv", type: "news",
    title: "Comic-Con panel schedule is out - here are the not-to-miss slots",
    subtitle: "Three major panels land on Saturday",
    summary: "Studios confirmed 46 panels across four days, with the biggest reveals stacked into Saturday afternoon.",
    body:
      "Saturday afternoon is the one to plan around: three studios are holding back-to-back panels with cast appearances.\n\nHall H tickets are already gone, but every main panel will be streamed and the replay is usually posted within a day.\n\nIf you are attending in person, arrive early - the queue for Hall H starts before sunrise.",
    image: `${IMG}/news_01.jpg`, author: "Fandom Verse Desk", source: "Convention Wire",
    tags: "ComicCon,Schedule,Panels", featured: 0, daysAgo: 9, views: 3980, likes: 288, comments: 40,
  },
  {
    fandom: "Comics", hub: "comics", type: "news",
    title: "Artist alley adds 40 new indie creators this year",
    subtitle: "Applications tripled",
    summary: "Organisers expanded the artist alley after applications tripled, adding a dedicated indie and zine hall.",
    body:
      "The new hall is a direct response to demand: applications were up 210% year over year.\n\nOrganisers also added a quiet hour for accessibility and a portfolio review desk staffed by working editors.\n\nSmall-press tables are already sold out, and the waitlist is open.",
    image: `${IMG}/news_04.jpg`, author: "Daniel Silva", source: "Convention Wire",
    tags: "ArtistAlley,Indie,Convention", featured: 0, daysAgo: 10, views: 2760, likes: 213, comments: 29,
  },
  {
    fandom: "Music", hub: "music", type: "article",
    title: "K-Pop comeback season survival guide",
    subtitle: "Five groups, three weeks, endless teasers",
    summary: "How to keep track of album drops, pre-orders and streaming goals without burning out.",
    body:
      "Comeback season can be overwhelming. Multiple groups release in the same window, teasers drop daily and every fandom has its own streaming target.\n\nThe trick is to pick two priorities: one group you follow closely and one playlist for everything else. Pre-order only what you will actually listen to.\n\nTake breaks from the timeline. The music will still be there tomorrow.",
    image: `${IMG}/news_05.jpg`, author: "Aisha Khan", source: "Idol Watch",
    tags: "KPop,Guide,Comeback", featured: 0, daysAgo: 12, views: 4210, likes: 356, comments: 47,
  },
  {
    fandom: "Sci-Fi", hub: "sci-fi", type: "deep_dive",
    title: "Advanced lore: the complete timeline explained",
    subtitle: "Deep Dive for expert fans",
    summary: "Every confirmed date, era and paradox in the saga, ordered and cross-referenced against on-screen evidence.",
    body:
      "The timeline has three distinct layers and the show only ever shows you two of them at once.\n\nLayer one is the founding era, which is referenced but never shown directly. Layer two is the current narrative. Layer three is the loop - the pieces that happen outside of chronological order and only make sense once you have finished the season.\n\nStart with the founding era. Everything that seems inconsistent later is a consequence of decisions made there.",
    image: `${FANDOM_IMG}/scifi.jpg`, author: "Fandom Verse Lore Team", source: "Deep Dive",
    tags: "Timeline,Lore,DeepDive", featured: 1, daysAgo: 11, views: 8640, likes: 918, comments: 132,
  },
  {
    fandom: "Anime", hub: "anime", type: "deep_dive",
    title: "Hidden trivia: 20 details you missed in the finale",
    subtitle: "Deep Dive for expert fans",
    summary: "Costume colours, background signage and one very deliberate continuity error, all explained.",
    body:
      "The finale rewards a second watch. Background characters from twenty episodes ago return for one frame each, and two of them wear the colours of a faction that had not been introduced yet.\n\nThere is also a signage detail in the town square that foreshadows the next arc. It is on screen for less than a second.\n\nFinally, keep an eye on the weather. Every major turning point in the series happens in the rain.",
    image: `${IMG}/news_07.jpg`, author: "Mei Tanaka", source: "Deep Dive",
    tags: "Trivia,EasterEggs,DeepDive", featured: 1, daysAgo: 13, views: 11200, likes: 1240, comments: 210,
  },
  {
    fandom: "Gaming", hub: "gaming", type: "deep_dive",
    title: "Character analysis: why the rival is the real protagonist",
    subtitle: "Deep Dive for expert fans",
    summary: "A close reading of the rival's arc, and what it says about the game's actual theme.",
    body:
      "The rival changes. The player does not. That inversion is the point of the story.\n\nLook at the soundtrack cues: the rival's theme is re-arranged three times, each version more hopeful than the last, while the player's theme stays identical.\n\nBy the final act, the game is asking you to notice that you have been the obstacle all along.",
    image: `${FANDOM_IMG}/gaming.jpg`, author: "Rahul Verma", source: "Deep Dive",
    tags: "Analysis,Story,DeepDive", featured: 0, daysAgo: 14, views: 5930, likes: 622, comments: 89,
  },
];

// ---------------------------------------------------------------------------
// galleries (each one carries its own media rows)
// ---------------------------------------------------------------------------
const GALLERIES = [
  {
    fandom: "Anime", hub: "anime",
    title: "Cosplay Showcase: Neo Tokyo Nights",
    subtitle: "42 cosplayers, one city",
    summary: "A night-time cosplay shoot across four locations, featuring hand-built props and LED armour.",
    image: `${IMG}/gallery_01.jpg`,
    author: "Fandom Verse Gallery", featured: 1, daysAgo: 2, views: 7420, likes: 812,
    captions: [
      "Neon alley group shot - the rain rig took an hour to set up",
      "LED armour detail, built over three months",
      "Backlit portrait at the station plaza",
      "Prop sword close-up - foam core over a 3D printed frame",
      "Stepping lights during the final sequence",
      "Wide shot of the full crew before wrap",
      "Reflection shot through the storefront glass",
      "Behind the scenes: umbrella rig for the rain scene",
      "Full ensemble group photo",
    ],
  },
  {
    fandom: "Anime", hub: "anime",
    title: "Fan Art Fridays: best of the week",
    subtitle: "Community picks",
    summary: "The community's favourite fan art submissions this week, from ink sketches to digital paintings.",
    image: `${IMG}/gallery_02.jpg`,
    author: "Fan Art Collectors", featured: 0, daysAgo: 5, views: 3980, likes: 640,
    captions: [
      "Ink study of the captain, 30 minute speed-draw",
      "Digital painting - soft light study",
      "Chibi sticker sheet by a first-time contributor",
      "Traditional watercolour with gold leaf accents",
      "Comic page layout experiment",
      "Colour key test for a fan animation short",
    ],
  },
  {
    fandom: "Movies & TV", hub: "movies-tv",
    title: "Convention floor highlights",
    subtitle: "Four halls, one weekend",
    summary: "Stage builds, prop exhibits and the cosplay parade captured across the convention floor.",
    image: `${IMG}/gallery_03.jpg`,
    author: "Convention Wire", featured: 1, daysAgo: 4, views: 5610, likes: 448,
    captions: [
      "Main stage build, before doors opened",
      "Prop exhibit: replica vehicles hall",
      "Cosplay parade line-up",
      "Panel queue stretching around the block",
      "Indie artist alley booths",
      "Evening closing ceremony lights",
    ],
  },
  {
    fandom: "Comics", hub: "comics",
    title: "Comic panel art spotlight",
    subtitle: "Process from thumbnails to ink",
    summary: "Six pages broken down step by step: thumbnails, pencils, inks and final colour.",
    image: `${IMG}/gallery_04.jpg`,
    author: "Panel & Ink Weekly", featured: 0, daysAgo: 7, views: 3120, likes: 356,
    captions: [
      "Rough thumbnails - 12 panels, 20 minutes",
      "Pencils with construction lines still visible",
      "Inked page with white-out corrections",
      "Flat colour pass",
      "Final page with lettering and sound effects",
      "Cover variant painted in gouache",
    ],
  },
  {
    fandom: "Music", hub: "music",
    title: "Lightstick ocean at the encore",
    subtitle: "Sold-out stadium, night two",
    summary: "Fan-taken shots of the synchronised lightstick wave during the encore stage.",
    image: `${IMG}/gallery_05.jpg`,
    author: "Idol Watch", featured: 1, daysAgo: 6, views: 9840, likes: 1520,
    captions: [
      "Pre-show, house lights still up",
      "First synchronised wave",
      "Encore stage with full lighting rig",
      "Fan banner project before the final song",
      "Confetti drop from the upper tier",
      "Post-show crowd still singing",
    ],
  },
  {
    fandom: "Gaming", hub: "gaming",
    title: "Esports arena grand final",
    subtitle: "Five games, full house",
    summary: "The view from the arena floor at the grand final, plus the trophy ceremony.",
    image: `${IMG}/gallery_06.jpg`,
    author: "Speedrun Community Board", featured: 0, daysAgo: 9, views: 4460, likes: 402,
    captions: [
      "Player booths before the first map",
      "Coaches reviewing the draft",
      "Main screen during the final game",
      "Trophy ceremony confetti",
      "Crowd wave between matches",
      "Post-match press area",
    ],
  },
];

// ---------------------------------------------------------------------------
// videos (simulated player - no external media required)
// ---------------------------------------------------------------------------
const VIDEOS = [
  {
    fandom: "Anime", hub: "anime", title: "Wano Arc Finale - Official Trailer",
    subtitle: "Official", summary: "The full finale trailer with the new opening theme.",
    image: `${IMG}/video_01.jpg`, author: "Studio Official", duration: 168, featured: 1,
    daysAgo: 1, views: 24100, likes: 2140, comments: 318,
    body: "Two minutes of the finale, cut to the new opening theme. The trailer confirms the episode count and the simulcast time for every region.",
  },
  {
    fandom: "Gaming", hub: "gaming", title: "How the world record run actually works",
    subtitle: "Commentated breakdown", summary: "Frame by frame breakdown of the skipped cutscene trick.",
    image: `${IMG}/video_02.jpg`, author: "Rahul Verma", duration: 750, featured: 1,
    daysAgo: 3, views: 13200, likes: 1180, comments: 204,
    body: "A full explainer of the route, including the two places where the run usually dies and how runners recover from a bad input.",
  },
  {
    fandom: "Movies & TV", hub: "movies-tv", title: "Season 3 teaser - frame by frame",
    subtitle: "Breakdown", summary: "Every hidden clue in the 90 second teaser, in order.",
    image: `${IMG}/video_03.jpg`, author: "Daniel Silva", duration: 495, featured: 1,
    daysAgo: 3, views: 8760, likes: 742, comments: 121,
    body: "We step through the teaser one frame at a time, starting with the insignia that started the whole theory.",
  },
  {
    fandom: "Anime", hub: "anime", title: "Cosplay transformation compilation",
    subtitle: "Community", summary: "Twelve cosplay transformations from the community showcase.",
    image: `${IMG}/video_04.jpg`, author: "Fandom Verse Gallery", duration: 302, featured: 0,
    daysAgo: 4, views: 15300, likes: 1980, comments: 176,
    body: "The community submission reel from this month's showcase, cut down to the twelve most-liked transformations.",
  },
  {
    fandom: "Gaming", hub: "gaming", title: "Grand final highlights",
    subtitle: "Esports", summary: "The fifth game comeback that decided the trophy.",
    image: `${IMG}/video_05.jpg`, author: "Speedrun Community Board", duration: 940, featured: 0,
    daysAgo: 8, views: 6790, likes: 588, comments: 94,
    body: "Extended highlights from the grand final, including the full draft of the deciding match.",
  },
  {
    fandom: "Comics", hub: "comics", title: "Behind the panels: indie artist interview",
    subtitle: "Interview", summary: "The award-winning creator talks process, crowdfunding and lettering.",
    image: `${IMG}/video_06.jpg`, author: "Panel & Ink Weekly", duration: 622, featured: 0,
    daysAgo: 10, views: 3240, likes: 341, comments: 52,
    body: "A 10 minute conversation about the workflow behind a self-published graphic novel, from script to print.",
  },
];

// ---------------------------------------------------------------------------
// podcasts
// ---------------------------------------------------------------------------
const PODCASTS = [
  {
    fandom: "Anime", hub: "anime", title: "The Wano Retrospective",
    subtitle: "Latest Episodes", summary: "Four years of production, reviewed episode by episode.",
    image: `${IMG}/podcast_01.jpg`, author: "Fandom Verse Podcast", duration: 2280,
    episode: 24, season: 3, featured: 1, daysAgo: 1, views: 5210, likes: 466, comments: 58,
    body: "We go back to the start of the arc and track how the animation style changed season by season, with two guest animators.",
  },
  {
    fandom: "Gaming", hub: "gaming", title: "Speedrunning culture",
    subtitle: "Latest Episodes", summary: "Why route discovery became a team sport.",
    image: `${IMG}/podcast_02.jpg`, author: "Fandom Verse Podcast", duration: 1980,
    episode: 25, season: 3, featured: 1, daysAgo: 3, views: 3980, likes: 352, comments: 44,
    body: "Three runners join us to talk about sharing routes, split files and the etiquette of a community record.",
  },
  {
    fandom: "Movies & TV", hub: "movies-tv", title: "Cinematic universes explained",
    subtitle: "Latest Episodes", summary: "How studios plan ten years of story before cameras roll.",
    image: `${IMG}/podcast_03.jpg`, author: "Fandom Verse Podcast", duration: 2460,
    episode: 26, season: 3, featured: 0, daysAgo: 4, views: 3320, likes: 288, comments: 37,
    body: "We break down the writers-room structure behind long-form cinematic universes and the cost of changing course mid-saga.",
  },
  {
    fandom: "Music", hub: "music", title: "Comeback season round table",
    subtitle: "Latest Episodes", summary: "Five fandoms, three weeks, honest thoughts.",
    image: `${IMG}/podcast_04.jpg`, author: "Idol Watch", duration: 2100,
    episode: 27, season: 3, featured: 1, daysAgo: 5, views: 6120, likes: 690, comments: 112,
    body: "A round table with one fan from each fandom about release schedules, streaming goals and how to avoid burnout.",
  },
  {
    fandom: "Comics", hub: "comics", title: "Indie comics rising",
    subtitle: "Latest Episodes", summary: "Self-publishing, crowdfunding and the new wave of indie books.",
    image: `${IMG}/podcast_05.jpg`, author: "Panel & Ink Weekly", duration: 1740,
    episode: 28, season: 3, featured: 0, daysAgo: 8, views: 2410, likes: 226, comments: 26,
    body: "Two self-published creators walk us through a crowdfunding campaign from concept art to shipping day.",
  },
  {
    fandom: "Sci-Fi", hub: "sci-fi", title: "Worldbuilding toolkit",
    subtitle: "Latest Episodes", summary: "The rules every great sci-fi universe follows.",
    image: `${IMG}/podcast_06.jpg`, author: "Fandom Verse Podcast", duration: 2640,
    episode: 29, season: 3, featured: 0, daysAgo: 9, views: 2980, likes: 264, comments: 31,
    body: "From internal consistency to the one rule every writer breaks on purpose - a practical look at worldbuilding.",
  },
];

// ---------------------------------------------------------------------------
// beginner fan glossary
// ---------------------------------------------------------------------------
const GLOSSARY = [
  ["Canon", "The official storyline accepted as part of a series' true narrative.", "General", "Story"],
  ["Headcanon", "A personal interpretation a fan treats as true, even without official support.", "General", "Story"],
  ["Shipping", "Supporting a romantic pairing between two characters.", "General", "Community"],
  ["OTP", "One True Pairing - the single ship a fan cares about most.", "General", "Community"],
  ["Fanart", "Artwork created by fans inspired by a series, character or pairing.", "General", "Creative"],
  ["Fanfic", "Fan-written fiction set inside an existing universe.", "General", "Creative"],
  ["Cosplay", "Dressing up as a character, usually with handmade costume and props.", "General", "Creative"],
  ["AMV", "Anime Music Video - a fan-made edit cutting footage to a song.", "Anime", "Creative"],
  ["Filler", "Episodes that do not advance the main story, often used by long-running shows.", "Anime", "Story"],
  ["Sub / Dub", "Subtitled (original audio) versus dubbed (re-recorded in another language).", "Anime", "Watching"],
  ["Speedrun", "Playing a game as fast as possible, usually with a shared route and split timings.", "Gaming", "Gaming"],
  ["Lore", "The accumulated backstory and world details of a franchise.", "General", "Story"],
  ["Bias", "In K-Pop, the member of a group a fan follows most closely.", "Music", "Community"],
  ["Comeback", "A K-Pop release cycle - new single or album plus promotions.", "Music", "Music"],
  ["Biome", "In gaming, a distinct region or environment type within a world.", "Gaming", "Gaming"],
  ["Retcon", "When a later work rewrites an earlier established fact.", "General", "Story"],
];

// ---------------------------------------------------------------------------

async function existingCount() {
  const row = await get(`SELECT COUNT(*) AS total FROM content_items`);
  return row ? row.total : 0;
}

async function seedArticles() {
  for (const item of ARTICLES) {
    const id = await upsert(item);
    if (id) {
      await run(
        `UPDATE content_items SET content_type = ?, subtitle = ?, body = ?, source = ?,
           duration_seconds = 0, episode_number = NULL WHERE id = ?`,
        [item.type, item.subtitle ?? null, item.body ?? null, item.source ?? null, id]
      );
    }
  }
}

async function seedGalleries() {
  for (const gallery of GALLERIES) {
    const id = await upsert({ ...gallery, type: "gallery" });
    if (!id) continue;

    const total = await get(
      `SELECT COUNT(*) AS total FROM content_media WHERE content_id = ?`,
      [id]
    );
    if (total && total.total > 0) continue;

    const captions = gallery.captions || [];
    for (let index = 0; index < captions.length; index += 1) {
      const tile = `${IMG}/gallery_${String((index % 9) + 1).padStart(2, "0")}.jpg`;
      await run(
        `INSERT INTO content_media (content_id, media_type, url, caption, sort_order)
         VALUES (?, 'image', ?, ?, ?)`,
        [id, tile, captions[index], index]
      );
    }
  }
}

async function seedVideos() {
  for (const video of VIDEOS) {
    await upsert({ ...video, type: "video" });
  }
}

async function seedPodcasts() {
  for (const podcast of PODCASTS) {
    const id = await upsert({
      ...podcast,
      type: "podcast",
      seconds: podcast.duration,
    });
    if (id) {
      await run(
        `UPDATE content_items SET episode_number = ?, season = ? WHERE id = ?`,
        [podcast.episode ?? null, podcast.season ?? null, id]
      );
    }
  }
}

/** Inserts (or refreshes) one content row and returns its id. */
async function upsert(item) {
  const row = await get(`SELECT id FROM content_items WHERE title = ?`, [item.title]);

  const values = [
    item.fandom,
    item.hub ?? null,
    item.type ?? "news",
    item.title,
    item.subtitle ?? null,
    item.summary ?? null,
    item.body ?? null,
    item.image ?? null,
    item.media ?? null,
    item.duration ?? item.seconds ?? 0,
    item.author ?? null,
    item.source ?? null,
    item.tags ?? null,
    item.views ?? 0,
    item.likes ?? 0,
    item.comments ?? 0,
    item.featured ?? 0,
    daysAgo(item.daysAgo ?? 1),
  ];

  if (row) {
    await run(
      `UPDATE content_items SET
         fandom = ?, hub_slug = ?, content_type = ?, title = ?, subtitle = ?, summary = ?,
         body = ?, image_url = ?, media_url = ?, duration_seconds = ?, author = ?, source = ?,
         tags = ?, views_count = ?, likes_count = ?, comments_count = ?, is_featured = ?,
         published_at = ?
       WHERE id = ?`,
      [...values, row.id]
    );
    return row.id;
  }

  const result = await run(
    `INSERT INTO content_items
     (fandom, hub_slug, content_type, title, subtitle, summary, body, image_url, media_url,
      duration_seconds, author, source, tags, views_count, likes_count, comments_count,
      is_featured, published_at)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
    values
  );
  return result.lastID;
}

async function seedGlossary() {
  for (const [term, definition, fandom, category] of GLOSSARY) {
    await run(
      `INSERT OR IGNORE INTO glossary_terms (term, definition, fandom, category)
       VALUES (?, ?, ?, ?)`,
      [term, definition, fandom, category]
    );
  }
}

/**
 * Recent history + offline cache for the demo account, so the "Recently
 * viewed" and "Offline content" rows of the Home dashboard are never empty.
 */
async function seedDemoHistory() {
  const user = await get(
    `SELECT id FROM users WHERE email = 'emma@fandomverse.com' LIMIT 1`
  );
  if (!user) return;

  const demo = [
    ["news", "One Piece", 0],
    ["video", "Wano", 1],
    ["podcast", "Retrospective", 1],
    ["news", "speedrun", 0],
    ["gallery", "Cosplay", 1],
    ["deep_dive", "Timeline", 0],
  ];

  for (const [type, keyword, offline] of demo) {
    const item = await get(
      `SELECT id FROM content_items
       WHERE content_type = ? AND title LIKE ?
       ORDER BY id LIMIT 1`,
      [type, `%${keyword}%`]
    );
    if (!item) continue;

    await run(
      `INSERT INTO content_views (user_id, content_id, is_offline, progress, viewed_at)
       VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP)
       ON CONFLICT (user_id, content_id) DO UPDATE SET
         is_offline = excluded.is_offline,
         viewed_at = CURRENT_TIMESTAMP`,
      [user.id, item.id, offline, offline ? 0.4 : 0.15]
    );
  }
}

async function refreshHubCounters() {
  const hubs = await all(`SELECT slug FROM fandom_hubs`);
  for (const hub of hubs) {
    const row = await get(
      `SELECT
         IFNULL(SUM(views_count), 0) AS views,
         COUNT(*) AS items
       FROM content_items WHERE hub_slug = ?`,
      [hub.slug]
    );
    if (!row) continue;
    await run(
      `UPDATE fandom_hubs
       SET posts_count = ?,
           followers_count = 1200 + (? / 40)
       WHERE slug = ?`,
      [row.items, row.views, hub.slug]
    );
  }
}

async function main() {
  console.log("MEMBER 2 - seeding Fandom Content data...");

  const before = await existingCount();
  console.log(`  existing content rows: ${before}`);

  await seedArticles();
  await seedGalleries();
  await seedVideos();
  await seedPodcasts();
  await seedGlossary();
  await refreshHubCounters();
  await seedDemoHistory();

  const after = await existingCount();
  const counts = await all(
    `SELECT content_type, COUNT(*) AS total FROM content_items GROUP BY content_type`
  );
  const media = await get(`SELECT COUNT(*) AS total FROM content_media`);
  const terms = await get(`SELECT COUNT(*) AS total FROM glossary_terms`);
  const views = await get(`SELECT COUNT(*) AS total FROM content_views`);

  console.log(`  content rows now: ${after}`);
  counts.forEach((c) => console.log(`    ${c.content_type}: ${c.total}`));
  console.log(`  gallery images : ${media ? media.total : 0}`);
  console.log(`  glossary terms : ${terms ? terms.total : 0}`);
  console.log(`  recent views   : ${views ? views.total : 0}`);
  console.log("Done.");
}

main().catch((error) => {
  console.error("Seed failed:", error);
  process.exitCode = 1;
});

export default main;
