/**
 * MEMBER 3 - Search & Community
 * Demo data seeder so the Search / Trending / Discussions / Bookmarks /
 * Notifications screens are never empty on first run.
 *
 * Run:  node database/seedCommunity.js
 *       (or)  npm run seed
 *
 * Safe to run multiple times - existing rows are skipped.
 */

import bcrypt from "bcrypt";
import db from "./db.js";
import { initCommunitySchema } from "./communitySchema.js";

initCommunitySchema();

const DEMO_PASSWORD = "Fandom@123";

const users = [
  { name: "Emma Carter",   email: "emma@fandomverse.com",   bio: "Anime addict | One Piece forever" },
  { name: "Rahul Verma",   email: "rahul@fandomverse.com",  bio: "Esports analyst & speedrunner" },
  { name: "Aisha Khan",    email: "aisha@fandomverse.com",  bio: "K-Pop multistan, cosplay lover" },
  { name: "Daniel Silva",  email: "daniel@fandomverse.com", bio: "Marvel lore expert & comic collector" },
  { name: "Mei Tanaka",    email: "mei@fandomverse.com",    bio: "Manga reviewer, jujutsu enthusiast" },
];

const posts = [
  {
    author: "emma@fandomverse.com",
    fandom: "Anime",
    title: "Naruto: Why the Pain arc is still peak writing",
    content:
      "The Pain arc works because the villain is a mirror of the hero. Nagato and Naruto both lost everything and had to choose between revenge and hope. Share your favourite moment below!",
    hashtags: "Anime,Naruto,Lore",
    type: "deep_dive",
    rating: 5,
  },
  {
    author: "rahul@fandomverse.com",
    fandom: "Gaming",
    title: "Community speedrunning: how fans break RPGs together",
    content:
      "Route discovery is a group sport now. People share frames, glitches and split files in real time and the record drops within hours. Discuss your favourite community route here.",
    hashtags: "Gaming,Speedrun,Esports",
    type: "deep_dive",
    rating: 4,
  },
  {
    author: "aisha@fandomverse.com",
    fandom: "Music",
    title: "K-Pop comeback season survival guide",
    content:
      "Five groups, three weeks, endless teasers. Here is how I keep track of album drops, pre-orders and streaming goals without burning out.",
    hashtags: "Music,KPop,Comeback",
    type: "post",
  },
  {
    author: "daniel@fandomverse.com",
    fandom: "Comics",
    title: "Best indie graphic novels to start with in 2025",
    content:
      "If you are tired of superhero crossovers, these self-contained indie books are perfect entry points. Drop your own recommendations in the comments!",
    hashtags: "Comics,Indie,Reading",
    type: "post",
  },
  {
    author: "mei@fandomverse.com",
    fandom: "Anime",
    title: "Jujutsu Kaisen: hidden details you probably missed",
    content:
      "The opening animation foreshadows events almost a full arc later. Let's collect all of the visual hints in one thread.",
    hashtags: "Anime,JujutsuKaisen,Lore",
    type: "deep_dive",
    rating: 5,
  },
  {
    author: "emma@fandomverse.com",
    fandom: "Movies & TV",
    title: "Sci-fi series worth bingeing before the finale",
    content:
      "Timeline-heavy shows hit different when you have the wiki open. This list stays spoiler free and covers the essentials only.",
    hashtags: "Movies,SciFi,Binge",
    type: "post",
  },
  {
    author: "rahul@fandomverse.com",
    fandom: "Sports",
    title: "Match-day watch parties: building a local fan club",
    content:
      "We started with four people and a projector. Two seasons later we fill a café. Here is exactly how we organised it.",
    hashtags: "Sports,FanClub,Community",
    type: "post",
  },
  {
    author: "aisha@fandomverse.com",
    fandom: "Sci-Fi",
    title: "Space opera timeline explained (no spoilers)",
    content:
      "Chronological order vs release order - which one should a new fan pick? I broke down both approaches with pros and cons.",
    hashtags: "SciFi,Lore,Guide",
    type: "deep_dive",
    rating: 4,
  },
];

const comments = [
  { postTitle: "Naruto: Why the Pain arc is still peak writing", author: "mei@fandomverse.com", body: "The swing scene breaks me every single rewatch." },
  { postTitle: "Naruto: Why the Pain arc is still peak writing", author: "daniel@fandomverse.com", body: "Peak foreshadowing. Kishimoto planned this from chapter one." },
  { postTitle: "Community speedrunning: how fans break RPGs together", author: "emma@fandomverse.com", body: "Split timers changed everything for the community." },
  { postTitle: "K-Pop comeback season survival guide", author: "emma@fandomverse.com", body: "Saving this, comeback season always wrecks my calendar." },
];

const fanclub = ["Anime", "Gaming", "Music", "Comics", "Sci-Fi"];

// ---------------------------------------------------------------------------
// banner artwork (generated by frontend/tool/generate_banner_art.py)
// ---------------------------------------------------------------------------
const FANDOM_BANNERS = {
  Anime: "assets/images/fandoms/anime.jpg",
  Gaming: "assets/images/fandoms/gaming.jpg",
  Music: "assets/images/fandoms/music.jpg",
  Comics: "assets/images/fandoms/comics.jpg",
  "Movies & TV": "assets/images/fandoms/movies_tv.jpg",
  Sports: "assets/images/fandoms/sports.jpg",
  "Sci-Fi": "assets/images/fandoms/scifi.jpg",
};
const DEFAULT_BANNER = "assets/images/fandoms/default.jpg";

function runAsync(sql, params = []) {
  return new Promise((resolve, reject) => {
    db.run(sql, params, function (err) {
      if (err) reject(err);
      else resolve(this);
    });
  });
}

function getAsync(sql, params = []) {
  return new Promise((resolve, reject) => {
    db.get(sql, params, (err, row) => {
      if (err) reject(err);
      else resolve(row);
    });
  });
}

async function seed() {
  const hash = await bcrypt.hash(DEMO_PASSWORD, 10);

  // ------------------------------ users ------------------------------
  for (const user of users) {
    const existing = await getAsync(`SELECT id FROM users WHERE email = ?`, [user.email]);

    if (!existing) {
      const result = await runAsync(
        `INSERT INTO users (name, email, password, verified, bio, followers_count, following_count)
         VALUES (?, ?, ?, 1, ?, 0, 0)`,
        [user.name, user.email, hash, user.bio]
      );
      console.log(`  + user: ${user.name}`);
      user.id = result.lastID;
    } else {
      user.id = existing.id;
    }
  }

  // --------------------------- user fandoms ---------------------------
  for (const user of users) {
    for (const fandom of fanclub.slice(0, 3)) {
      await runAsync(`INSERT OR IGNORE INTO user_fandoms (user_id, fandom) VALUES (?, ?)`, [
        user.id,
        fandom,
      ]);
    }
  }

  const idByEmail = Object.fromEntries(users.map((u) => [u.email, u.id]));

  // ------------------------------ posts -------------------------------
  for (const post of posts) {
    const existing = await getAsync(`SELECT id FROM posts WHERE title = ?`, [post.title]);
    if (existing) {
      post.id = existing.id;
      continue;
    }

    const result = await runAsync(
      `INSERT INTO posts
         (user_id, fandom_category, title, content, hashtags, post_type, rating,
          likes_count, views_count, image_url)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [
        idByEmail[post.author],
        post.fandom,
        post.title,
        post.content,
        post.hashtags,
        post.type,
        post.rating || 0,
        Math.floor(Math.random() * 40) + 5,
        Math.floor(Math.random() * 300) + 40,
        FANDOM_BANNERS[post.fandom] || DEFAULT_BANNER,
      ]
    );
    post.id = result.lastID;
    console.log(`  + post: ${post.title}`);
  }

  // banner artwork: keeps existing databases in sync too
  for (const [fandom, banner] of Object.entries(FANDOM_BANNERS)) {
    await runAsync(`UPDATE posts SET image_url = ? WHERE fandom_category = ?`, [
      banner,
      fandom,
    ]);
  }
  await runAsync(`UPDATE posts SET image_url = ? WHERE image_url IS NULL`, [
    DEFAULT_BANNER,
  ]);

  // ---------------------------- comments ------------------------------
  for (const comment of comments) {
    const post = posts.find((p) => p.title === comment.postTitle);
    if (!post?.id) continue;

    const existing = await getAsync(
      `SELECT id FROM comments WHERE post_id = ? AND body = ?`,
      [post.id, comment.body]
    );
    if (existing) continue;

    await runAsync(`INSERT INTO comments (post_id, user_id, body) VALUES (?, ?, ?)`, [
      post.id,
      idByEmail[comment.author],
      comment.body,
    ]);
  }

  // keep counters in sync
  await runAsync(
    `UPDATE posts SET comments_count =
       (SELECT COUNT(*) FROM comments c WHERE c.post_id = posts.id)`
  );

  // ------------------------------ follows -----------------------------
  for (const user of users) {
    for (const other of users) {
      if (user.id === other.id) continue;
      await runAsync(
        `INSERT OR IGNORE INTO follows (follower_id, following_id) VALUES (?, ?)`,
        [user.id, other.id]
      );
    }
  }

  await runAsync(
    `UPDATE users SET
       followers_count = (SELECT COUNT(*) FROM follows f WHERE f.following_id = users.id),
       following_count = (SELECT COUNT(*) FROM follows f WHERE f.follower_id  = users.id)`
  );

  // --------------------------- notifications --------------------------
  const emmaId = idByEmail["emma@fandomverse.com"];
  const notifCount = await getAsync(
    `SELECT COUNT(*) AS c FROM notifications WHERE user_id = ?`,
    [emmaId]
  );

  if (!notifCount.c) {
    const samples = [
      [idByEmail["rahul@fandomverse.com"], "follow", "Rahul Verma started following you"],
      [idByEmail["mei@fandomverse.com"], "like", "Mei Tanaka liked your post"],
      [idByEmail["aisha@fandomverse.com"], "comment", "Aisha Khan commented on your post"],
      [idByEmail["daniel@fandomverse.com"], "bookmark", "Daniel Silva saved your post"],
      [null, "system", "Welcome to FANDOM VERSE! Complete a Deep Dive to earn your first badge."],
    ];

    for (const [actorId, type, message] of samples) {
      await runAsync(
        `INSERT INTO notifications (user_id, actor_id, type, message, is_read)
         VALUES (?, ?, ?, ?, 0)`,
        [emmaId, actorId, type, message]
      );
    }
    console.log("  + notifications for Emma Carter");
  }

  console.log("\n✅ Community seed complete.");
  console.log(`   Demo login : emma@fandomverse.com  /  ${DEMO_PASSWORD}`);
  console.log(`   All demo users share the password: ${DEMO_PASSWORD}\n`);

  db.close();
}

seed().catch((error) => {
  console.error("Seed failed:", error.message);
  db.close();
});
