import 'package:flutter/material.dart';

/// Shared image widget used by every Member 1 / Member 2 screen.
///
/// Resolution order:
///   1. bundled asset (`assets/...`) - artwork generated by
///      `frontend/tool/generate_banner_art.py`
///   2. remote `http(s)` URL
///   3. animated brand gradient fallback
///
/// The image fades + scales in when it becomes available, which keeps long
/// lists feeling smooth instead of popping.
class AppImage extends StatelessWidget {
  final String? path;
  final double? height;
  final double? width;
  final BoxFit fit;
  final BorderRadius? borderRadius;
  final List<Color>? fallbackColors;
  final IconData fallbackIcon;
  final bool showFade;

  const AppImage({
    super.key,
    required this.path,
    this.height,
    this.width,
    this.fit = BoxFit.cover,
    this.borderRadius,
    this.fallbackColors,
    this.fallbackIcon = Icons.auto_awesome_rounded,
    this.showFade = true,
  });

  bool get _isAsset => (path ?? '').trim().startsWith('assets/');
  bool get _isRemote {
    final value = (path ?? '').trim();
    return value.startsWith('http://') || value.startsWith('https://');
  }

  @override
  Widget build(BuildContext context) {
    final corners = borderRadius ?? BorderRadius.circular(0);

    Widget child;
    if (_isAsset) {
      child = Image.asset(
        path!,
        height: height,
        width: width,
        fit: fit,
        errorBuilder: (_, _, _) => _fallback(),
      );
    } else if (_isRemote) {
      child = Image.network(
        path!,
        height: height,
        width: width,
        fit: fit,
        loadingBuilder: (context, inner, progress) =>
            progress == null ? inner : _fallback(),
        errorBuilder: (_, _, _) => _fallback(),
      );
    } else {
      child = _fallback();
    }

    if (!showFade) return ClipRRect(borderRadius: corners, child: child);

    return ClipRRect(
      borderRadius: corners,
      child: AnimatedSwitcher(
        duration: const Duration(milliseconds: 380),
        switchInCurve: Curves.easeOutCubic,
        transitionBuilder: (widget, animation) => FadeTransition(
          opacity: animation,
          child: ScaleTransition(
            scale: Tween<double>(begin: 1.04, end: 1.0).animate(animation),
            child: widget,
          ),
        ),
        child: child,
      ),
    );
  }

  Widget _fallback() {
    final colors =
        fallbackColors ?? const [Color(0xFF7C3AED), Color(0xFFEC4899)];
    return Container(
      height: height,
      width: width,
      decoration: BoxDecoration(
        gradient: LinearGradient(
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
          colors: colors,
        ),
      ),
      child: Stack(
        alignment: Alignment.center,
        children: [
          Positioned(
            right: -18,
            bottom: -18,
            child: Icon(
              fallbackIcon,
              size: 96,
              color: Colors.white.withValues(alpha: 0.16),
            ),
          ),
          Icon(fallbackIcon, size: 28, color: Colors.white.withValues(alpha: 0.75)),
        ],
      ),
    );
  }
}

/// Circular avatar: bundled avatar preset, remote URL, or the user's initial
/// on a brand gradient.
class AppAvatar extends StatelessWidget {
  final String? path;
  final String name;
  final double radius;
  final Color ringColor;
  final bool showRing;

  const AppAvatar({
    super.key,
    required this.path,
    required this.name,
    this.radius = 26,
    this.ringColor = const Color(0xFF3B82F6),
    this.showRing = true,
  });

  String get _initial =>
      name.trim().isEmpty ? 'U' : name.trim()[0].toUpperCase();

  bool get _usable {
    final value = (path ?? '').trim();
    return value.startsWith('assets/') ||
        value.startsWith('http://') ||
        value.startsWith('https://');
  }

  @override
  Widget build(BuildContext context) {
    final avatar = ClipOval(
      child: SizedBox(
        width: radius * 2,
        height: radius * 2,
        child: _usable
            ? AppImage(path: path, fit: BoxFit.cover, borderRadius: BorderRadius.circular(radius))
            : _initialAvatar(),
      ),
    );

    if (!showRing) return avatar;

    return Container(
      padding: const EdgeInsets.all(2),
      decoration: BoxDecoration(
        shape: BoxShape.circle,
        gradient: LinearGradient(
          colors: [ringColor, ringColor.withValues(alpha: 0.35)],
        ),
      ),
      child: avatar,
    );
  }

  Widget _initialAvatar() {
    return Container(
      decoration: const BoxDecoration(
        gradient: LinearGradient(
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
          colors: [Color(0xFF3B82F6), Color(0xFF8B5CF6)],
        ),
      ),
      alignment: Alignment.center,
      child: Text(
        _initial,
        style: TextStyle(
          color: Colors.white,
          fontSize: radius * 0.8,
          fontWeight: FontWeight.bold,
        ),
      ),
    );
  }
}
