import 'package:flutter/material.dart';
import '../theme/app_theme.dart';

/// MEMBER 3 - Search & Community
/// Banner artwork shown on community post cards and the post details screen.
///
/// `assets/...` paths come from the bundled artwork generated by
/// frontend/tool/generate_banner_art.py. Remote http(s) URLs also work, and
/// anything unusable falls back to a fandom coloured gradient.
class CommunityBannerImage extends StatelessWidget {
  final String? imageUrl;
  final String fandom;
  final double height;
  final BorderRadius? borderRadius;

  const CommunityBannerImage({
    super.key,
    required this.imageUrl,
    required this.fandom,
    this.height = 140,
    this.borderRadius,
  });

  /// Colour used for the gradient fallback of each fandom.
  static Color fandomColor(String fandom) {
    switch (fandom) {
      case 'Anime':
        return const Color(0xFFEC4899);
      case 'Gaming':
        return const Color(0xFF3B82F6);
      case 'Movies & TV':
        return const Color(0xFFF59E0B);
      case 'Comics':
        return const Color(0xFFF97316);
      case 'Music':
        return const Color(0xFF10B981);
      case 'Sports':
        return const Color(0xFFEF4444);
      case 'Sci-Fi':
        return const Color(0xFF8B5CF6);
      default:
        return AppTheme.primaryColor;
    }
  }

  /// Bundled banner for a fandom (fallback when the post has no image).
  static String bannerFor(String fandom) {
    switch (fandom) {
      case 'Anime':
        return 'assets/images/fandoms/anime.jpg';
      case 'Gaming':
        return 'assets/images/fandoms/gaming.jpg';
      case 'Movies & TV':
        return 'assets/images/fandoms/movies_tv.jpg';
      case 'Comics':
        return 'assets/images/fandoms/comics.jpg';
      case 'Music':
        return 'assets/images/fandoms/music.jpg';
      case 'Sports':
        return 'assets/images/fandoms/sports.jpg';
      case 'Sci-Fi':
        return 'assets/images/fandoms/scifi.jpg';
      default:
        return 'assets/images/fandoms/default.jpg';
    }
  }

  String get _resolved {
    final url = (imageUrl ?? '').trim();
    return url.isEmpty ? bannerFor(fandom) : url;
  }

  bool get _isAsset => _resolved.startsWith('assets/');
  bool get _isRemote =>
      _resolved.startsWith('http://') || _resolved.startsWith('https://');

  @override
  Widget build(BuildContext context) {
    final corners = borderRadius ?? BorderRadius.circular(14);

    Widget content;
    if (_isAsset) {
      content = Image.asset(
        _resolved,
        height: height,
        width: double.infinity,
        fit: BoxFit.cover,
        errorBuilder: (_, __, ___) => _fallback(),
      );
    } else if (_isRemote) {
      content = Image.network(
        _resolved,
        height: height,
        width: double.infinity,
        fit: BoxFit.cover,
        loadingBuilder: (context, child, progress) =>
            progress == null ? child : _fallback(),
        errorBuilder: (_, __, ___) => _fallback(),
      );
    } else {
      content = _fallback();
    }

    return ClipRRect(
      borderRadius: corners,
      child: SizedBox(
        height: height,
        width: double.infinity,
        child: Stack(
          fit: StackFit.expand,
          children: [
            content,
            // keeps overlaid chips readable
            DecoratedBox(
              decoration: BoxDecoration(
                gradient: LinearGradient(
                  begin: Alignment.topCenter,
                  end: Alignment.bottomCenter,
                  colors: [
                    Colors.black.withValues(alpha: 0.12),
                    Colors.transparent,
                    Colors.black.withValues(alpha: 0.45),
                  ],
                  stops: const [0.0, 0.5, 1.0],
                ),
              ),
            ),
            Positioned(
              left: 10,
              bottom: 8,
              child: Row(
                children: [
                  const Icon(Icons.tag_rounded, size: 12, color: Colors.white70),
                  const SizedBox(width: 4),
                  Text(
                    fandom.toUpperCase(),
                    style: const TextStyle(
                      color: Colors.white,
                      fontSize: 9.5,
                      fontWeight: FontWeight.bold,
                      letterSpacing: 1,
                      shadows: [Shadow(color: Colors.black54, blurRadius: 6)],
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _fallback() {
    final color = fandomColor(fandom);

    return Container(
      height: height,
      width: double.infinity,
      decoration: BoxDecoration(
        gradient: LinearGradient(
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
          colors: [color, color.withValues(alpha: 0.55), AppTheme.cardColor],
        ),
      ),
      child: Center(
        child: Icon(
          Icons.auto_awesome_rounded,
          size: height * 0.4,
          color: Colors.white.withValues(alpha: 0.25),
        ),
      ),
    );
  }
}
