import 'package:flutter/material.dart';
import '../theme/event_theme.dart';

/// MEMBER 4 - Events & Maps
/// Renders an event banner image.
///
/// Handles all three cases so the UI never shows a broken image:
///   * `assets/...`      -> bundled artwork (generated by
///                          frontend/tool/generate_banner_art.py)
///   * `http(s)://...`   -> remote image, loaded with a placeholder
///   * anything else     -> gradient + category icon fallback
class EventBannerImage extends StatelessWidget {
  final String? imageUrl;
  final String category;
  final double height;
  final BorderRadius? borderRadius;

  /// Dark scrim on top of the artwork so overlaid text stays readable.
  final bool scrim;

  /// Extra overlay drawn above the image (e.g. the date badge).
  final Widget? overlay;

  /// Icon shown on the gradient fallback.
  final bool showFallbackIcon;

  const EventBannerImage({
    super.key,
    required this.imageUrl,
    required this.category,
    this.height = 120,
    this.borderRadius,
    this.scrim = true,
    this.overlay,
    this.showFallbackIcon = true,
  });

  /// The image that will actually be loaded: the event's own [imageUrl] when
  /// present, otherwise the bundled artwork of its category.
  String get _resolved {
    final url = (imageUrl ?? '').trim();
    return url.isEmpty ? EventTheme.bannerFor(category) : url;
  }

  bool get _isAsset => _resolved.startsWith('assets/');
  bool get _isRemote =>
      _resolved.startsWith('http://') || _resolved.startsWith('https://');

  @override
  Widget build(BuildContext context) {
    final corners = borderRadius ?? BorderRadius.circular(18);

    Widget content;
    if (_isAsset) {
      content = Image.asset(
        _resolved,
        height: height,
        width: double.infinity,
        fit: BoxFit.cover,
        errorBuilder: (_, _, _) => _fallback(),
      );
    } else if (_isRemote) {
      content = Image.network(
        _resolved,
        height: height,
        width: double.infinity,
        fit: BoxFit.cover,
        loadingBuilder: (context, child, progress) =>
            progress == null ? child : _fallback(),
        errorBuilder: (_, _, _) => _fallback(),
      );
    } else {
      content = _fallback();
    }

    return ClipRRect(
      borderRadius: corners,
      child: SizedBox(
        height: height,
        width: double.infinity,
        child: Stack(
          fit: StackFit.expand,
          children: [
            content,
            if (scrim)
              DecoratedBox(
                decoration: BoxDecoration(
                  gradient: LinearGradient(
                    begin: Alignment.topCenter,
                    end: Alignment.bottomCenter,
                    colors: [
                      Colors.black.withValues(alpha: 0.18),
                      Colors.transparent,
                      Colors.black.withValues(alpha: 0.55),
                    ],
                    stops: const [0.0, 0.45, 1.0],
                  ),
                ),
              ),
            ?overlay,
          ],
        ),
      ),
    );
  }

  /// Category coloured gradient used when there is no usable image.
  Widget _fallback() {
    final color = EventTheme.categoryColor(category);

    return Container(
      height: height,
      width: double.infinity,
      decoration: BoxDecoration(
        gradient: LinearGradient(
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
          colors: [color, color.withValues(alpha: 0.6), const Color(0xFF10141C)],
        ),
      ),
      child: showFallbackIcon
          ? Center(
              child: Icon(
                EventTheme.categoryIcon(category),
                size: height * 0.42,
                color: Colors.white.withValues(alpha: 0.28),
              ),
            )
          : null,
    );
  }
}
