import 'package:flutter/material.dart';

import '../theme/shop_theme.dart';
import 'shop_animated.dart';

/// MEMBER 5 - Merchandise Store
/// Renders a product image from whatever `products.image_url` contains:
///
/// | `image_url` value      | Rendering                                    |
/// |------------------------|----------------------------------------------|
/// | `assets/...`           | bundled artwork (`Image.asset`)              |
/// | `http(s)://...`        | remote image with a loading placeholder      |
/// | empty / broken         | category coloured gradient + category icon   |
///
/// All bundled artwork is generated by
/// `frontend/tool/generate_product_art.py`, so no external image host is
/// required and the store works completely offline.
class ProductImage extends StatelessWidget {
  final String? imageUrl;
  final String category;
  final String? name;
  final double? width;
  final double? height;
  final BoxFit fit;
  final double radius;

  /// Adds the travelling light sweep (used on the larger hero images).
  final bool animated;

  const ProductImage({
    super.key,
    required this.imageUrl,
    this.category = '',
    this.name,
    this.width,
    this.height,
    this.fit = BoxFit.cover,
    this.radius = 16,
    this.animated = false,
  });

  @override
  Widget build(BuildContext context) {
    final content = _buildContent();

    return ClipRRect(
      borderRadius: BorderRadius.circular(radius),
      child: SizedBox(
        width: width,
        height: height,
        child: animated
            ? ShineSweep(
                opacity: 0.16,
                period: const Duration(milliseconds: 3400),
                child: content,
              )
            : content,
      ),
    );
  }

  Widget _buildContent() {
    if (ShopTheme.isAsset(imageUrl)) {
      return Image.asset(
        imageUrl!,
        fit: fit,
        width: width,
        height: height,
        // A missing file falls back to the category gradient rather than
        // showing the red "asset not found" box.
        errorBuilder: (context, error, stack) => _fallback(),
      );
    }

    if (ShopTheme.isRemote(imageUrl)) {
      return Image.network(
        imageUrl!,
        fit: fit,
        width: width,
        height: height,
        loadingBuilder: (context, child, progress) {
          if (progress == null) return child;
          return _placeholder(progress);
        },
        errorBuilder: (context, error, stack) => _fallback(),
      );
    }

    return _fallback();
  }

  /// Handles an asset that is empty or failed to load.
  Widget _fallback() {
    // Most bundled products exist, so try the generic catalogue artwork
    // before giving up on a picture entirely.
    return Image.asset(
      ShopTheme.fallbackProductImage,
      fit: fit,
      width: width,
      height: height,
      errorBuilder: (context, error, stack) => _gradientFallback(),
    );
  }

  /// Last resort: a category-coloured gradient with the category icon.
  Widget _gradientFallback() {
    final color = ShopTheme.categoryColor(category);

    return DecoratedBox(
      decoration: BoxDecoration(
        gradient: LinearGradient(
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
          colors: [
            color.withValues(alpha: 0.85),
            color.withValues(alpha: 0.35),
            ShopTheme.surface,
          ],
        ),
      ),
      child: Center(
        child: Icon(
          ShopTheme.categoryIcon(category),
          size: 42,
          color: Colors.white.withValues(alpha: 0.55),
        ),
      ),
    );
  }

  Widget _placeholder(ImageChunkEvent progress) {
    final expected = progress.expectedTotalBytes;
    final value = expected != null && expected > 0
        ? progress.cumulativeBytesLoaded / expected
        : null;

    return ColoredBox(
      color: ShopTheme.surfaceLight,
      child: Center(
        child: SizedBox(
          width: 26,
          height: 26,
          child: CircularProgressIndicator(
            value: value,
            strokeWidth: 2.4,
            color: ShopTheme.primary,
          ),
        ),
      ),
    );
  }
}
